# The URL the site will be built for
base_url = "https://rndlabs.xyz"
title = "rndlabs.xyz"
description = "Collaborative public goods."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    {name = "tags"}
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Set our theme
theme = "website-theme"

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]

# One of: blue, green, orange, pink, red.
# Defaults to blue.
accent_color = "pink"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "dark"

# The logo text - defaults to "Terminimal theme"
logo_text = "rndlabs"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "rndlabs.eth"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
#copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "home", url = "$BASE_URL"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    # {name = "tags", url = "$BASE_URL/tags"},
    # {name = "archive", url = "$BASE_URL/archive"},
    # {name = "about", url = "$BASE_URL/about"},
    # {name = "contributors", url = "$BASE_URL/contributors"},

    # set newtab to true to make the link open in new tab
    {name = "contributors", url = "$BASE_URL/contributors", newtab = false},
    {name = "white paper", url = "https://github.com/rndlabs/white-paper/blob/main/rndlabs%20White%20Paper.md", newtab= true},
    {name = "docs", url = "https://sep.rndlabs.xyz", newtab= true},
    {name = "github", url = "https://github.com/rndlabs", newtab = true},
    {name = "discord", url = "https://discord.gg/Zz3er45Vc9", newtab= true}
]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.

favicon = "/favicon.png"